### PR TITLE
Rochester add Friday slot

### PR DESCRIPTION
**Pull request by kyliemulholland**
Waiting for Jenkins to come alive before I can test in preprod...

### CODE REVIEW

**Comment by SteveMarshall** [comment]
Well, I think @dan-palmer, @threeedaymonk, and I all knew this day would come. The tests are failing here, @kyliemulholland, because they depend on Rochester's visit slots never changing. One of us is going to have to update the tests to fix that problem.

**Comment by threedaymonk** [comment]
Rebased onto master (so that the tests won't be broken by this).

**Comment by kyliemulholland** [comment]
Can I deploy to production?

**Comment by kyliemulholland** [comment]
Tested on preprod - passed.

**Comment by SteveMarshall** [comment]
@kyliemulholland Merged. :boom:

**Pull request merged**
