### PR TITLE
Ping.json

### PR DESCRIPTION
**Pull request by dotemacs**
Refactored the way ping.json is being generated. Reusing the same mechanism that is used on Fee Remission & Parliamentary Questions projects.

### CODE REVIEW

**Comment by threedaymonk** [comment]
I think the change is fine, but I'm going to hold off on merging this until the associated environment changes have been made.

**Comment by ashb** [comment]
I don't think the related change to environment has been done so this shouldn't be merged yet.

**Comment by SteveMarshall** [comment]
I *think* this PR is unnecessary now? [`PingController`](https://github.com/ministryofjustice/prison-visits/blob/master/app/controllers/ping_controller.rb) has all the features this offers, I think?

**Comment by dan-palmer** [comment]
@SteveMarshall Appears to me also that `PingController` has the functionality of this PR. Should we bin it?

**Comment by threedaymonk** [comment]
Closing as discussed.

**Pull request closed without merging**
