### PR TITLE
Remove trailing commas from last array elements

### PR DESCRIPTION
**Pull request by tatyree**
Recap: discussion between the team resulted in the decision that last-comma usage would follow the prevailing style of the app.  On investigation, I discovered that there were 17 rubocop violations for trailing commas, but 140 examples of arrays without trailing commas.  Based on this information and the team discussion, this commit is ready to be merged.

### CODE REVIEW

**Comment by SteveMarshall** [comment]
Wait, rubocop objects to trailing commas? Really? Do they hate clean diffs? :frowning:

**Comment by tatyree** [comment]
It objects to commas on last array elements: [1, 2, 3,]...

**Comment by dan-palmer** [comment]
:boom: conflicts :cry:

**Comment by tatyree** [comment]
Grrr. Conflicts.

**Comment by SteveMarshall** [comment]
@tatyree Yeah, that's what I mean: I've always been of the view that things should *always* have a trailing comma so that adding a new item doesn't show as a change to two lines. I'm not sure I'm a fan of this rubocop rule.

**Comment by tatyree** [comment]
Ah, @SteveMarshall I see...I'd never thought about it that way.

**Comment by SteveMarshall** [comment]
The other argument I just mentioned is that, when re-ordering a multi-line array/hash/whatever, it's less likely, with a trailing comma, to break the code.

**Comment by SteveMarshall** [comment]
@threedaymonk @dan-palmer You guys got any feelings either way on this one?

**Comment by threedaymonk** [comment]
Looks fine to me.

**Pull request merged**
