### PR TITLE
Proxy certain paths to new app (prototype)

### PR DESCRIPTION
**Pull request by mloughran**
Prototypes the use of rack-proxy for this.

To test it out, provide the optional configuration variable which enables the proxying functionality.

		NEW_APP_URL=http://localhost:3000/ rails s -p 3001

This has uncovered a few issues:

* What to do about assets? Currently I've found yet another way to generate unstyled pages...
* What about HTTPS requests? Should they be proxied over SSL?

The paths to proxy currently hardcoded as /en/... and /cy/...

### CODE REVIEW

**Comment by mloughran** [comment]
To answer my question, `config.asset_host` is the obvious answer. Aren't we already uploading assets to S3?

**Comment by threedaymonk** [comment]
This *doesn't* work when proxying to an HTTPS server. I can't immediately find the solution.

**Comment by mloughran** [comment]
My conclusion is that we should use nginx for this if we can.

**Comment by threedaymonk** [comment]
As we've settled on nginx for proxying, I'm going to close this.

**Pull request closed without merging**
