### PR TITLE
Cardiff october unbookable dates

### PR DESCRIPTION
**Pull request by kyliemulholland**

### CODE REVIEW

**Comment by kyliemulholland** [comment]
@dan-palmer I've tried to test on Preprod but Cardiff have a really short maximum leadtime (much less than 28 days) so I've been unable to test.
Can you show me what to do these instances?

**Comment by dan-palmer** [comment]
@kyliemulholland can have a look on my laptop when you are free - just give me a shout

**Comment by kyliemulholland** [comment]
@dan-palmer Can you merge or is there an issue?

**Comment by dan-palmer** [comment]
screen shot 2015-09-24 at 13 46 36
screen shot 2015-10-19 at 13 49 00

confirmed as working

**Pull request merged**
