### PR TITLE
Add Rubocop to enforce styling on code

### PR DESCRIPTION
**Pull request by EGiataganas**
We added the Rubocop gem and then generated the
rubocop todo list which gives us a lot of issues
to address.

### CODE REVIEW

**Comment by dan-palmer** [comment]
Take care with these tidy-ups/refactorings - the team might not be keen on following the guide exactly. If you aren't sure just ask.

**Comment by EGiataganas** [comment]
@dan-palmer Thanks dude! I will :+1:

**Comment by threedaymonk** [comment]
My opinions on Rubocop settings are here: https://github.com/ministryofjustice/case_file_editor/blob/master/.rubocop.yml

**Comment by EGiataganas** [comment]
@threedaymonk :+1:

**Comment by dan-palmer** [comment]
@threedaymonk sweet :sunglasses:

**Comment by EGiataganas** [comment]
@threedaymonk I've just added the Rubocop settings as you suggested :+1:

**Comment by EGiataganas** [comment]
@threedaymonk , @dan-palmer As you can see I split Paul's suggestions for rubocop settings into two different files. I tried to have everything into one file, even with adding to TODO file that
```ruby
Metrics/LineLength:
  Exclude:
    - 'app/controllers/application_controller.rb'
```
but it didn't worked. Please let me know if you have any more suggestions.

**Comment by threedaymonk** [comment]
@EGiataganas You'll need to add exclusions for all the files that don't match, rather like the automatically generated ones you already have. It might even be possible to get Rubocop to regenerate the todo file.

**Comment by EGiataganas** [comment]
@threedaymonk thanks!

**Comment by SteveMarshall** [comment]
@EGiataganas Can the rubocop branch for this PR be deleted?

**Pull request merged**
