### PR TITLE
New timeout prompt

### PR DESCRIPTION
**Pull request by matharden**
Fixes 78804070

- appears after 17 minutes
- puts focus on alert UI when it appears
- extend timeout now works when user chooses to extend
- redirects to /abandon after a further 3 minutes if time not extended
- does not change interface
- timeout prompt moved to [MOJ TimeoutPrompt](https://github.com/ministryofjustice/moj-timeoutprompt) for reuse and included via Bower

### CODE REVIEW

**Comment by jasiek** [comment]
Assuming handlebars is a gem here, would it not make sense to just drop it in the Gemfile?

**Comment by matharden** [comment]
Handlebars is a front-end asset which is included with bower automatically as it's a dependancy of TimeoutPrompt.

**Comment by SteveMarshall** [comment]
This looks ready to :ship: to me. Do @nicolekobilansky or @leighmoney need to review the prompt?

**Comment by matharden** [comment]
Correct, we need @leighmoney to review the explanation of what happens when it "times out".

See https://github.com/ministryofjustice/prison-visits/pull/147/files#diff-6

**Comment by matharden** [comment]
And @leighmoney, while you're looking please review the content of [timeout](https://github.com/ministryofjustice/prison-visits/pull/147/files#diff-5) and refer to the [Civil Claims timeout](https://designpatterns.hackpad.com/Modal-dialog-boxes-ZJNqssq4Dll#:h=Civil-claims).

**Comment by SteveMarshall** [comment]
This looks like it's ready to :ship: now. I shall merge on Monday!

**Pull request merged**
