### PR TITLE
Fix CSRF protection at the ApplicationController

### PR DESCRIPTION
**Pull request by EGiataganas**
Fix the implementation of CSFR protection at thet Application Level by
setting `protect_from_forgery with: :exception` in the
`ApplicationController`

### CODE REVIEW

**Comment by EGiataganas** [comment]
@SteveMarshall Tested on preprod!

**Comment by dan-palmer** [comment]
This is fine but it would be nice if we could test it. 

Its kind of fiddly to test through a feature test but perhaps we could do something with the `forgery_protection_strategy` config value that `ActionController::Base` has. Calling this should return whatever the strategy is if it has been set in the controller or nil. Perhaps we could have a shared example that all the controller tests have that asserts forgery protection is enabled. Its quite implementation specific doing it this way but I can't think of an alternate thats cleaner off the top of my head.

Thoughts @SteveMarshall, @threedaymonk ?

**Comment by SteveMarshall** [comment]
@dan-palmer I'm not sure that would work: we disable forgery protection in the tests, so any tests checking it would find it disabled and, because it's set in config, it's set (unless I'm mistaken?) for the lifetime of the rails server (and, by extension, the lifetime of the test run?), so we can't change it (as @EGiataganas and I discovered yesterday) mid-test.

I'd like to test this, but I'm not sure I can see a clear way to do that.

**Comment by threedaymonk** [comment]
Personally, I'm not convinced of the necessity of testing code that is merely declarative, and as this is set in the top-level controller from which all others derive, I don't think there's a lot of value in testing each controller.

I'm happy to take it on trust that Rails works as designed – or, at least, that CSRF protection is tested in more detail in Rails than we'd ever do in our application's suite.

However, the tests run just fine with

```ruby
config.action_controller.allow_forgery_protection = true
```

so I think the option is there if you want it.

**Comment by EGiataganas** [comment]
@threedaymonk Yesterday @SteveMarshall and I we were trying to fake the 
```
config.action_controller.allow_forgery_protection = true
```
by making that <a href="https://gist.github.com/EGiataganas/2141370e2457e157b699">gist</a> using around. But we could find 
```
<input type="hidden" name="authenticity_token" value="">
```
so we couldn't test it. I'm happy too, to take it on trust that Rails works as designed – or, at least, that CSRF protection is tested in more detail in Rails than we'd ever do in our application's suite.

**Comment by dan-palmer** [comment]
:ship:

**Comment by threedaymonk** [comment]
I'm happy to merge this.

**Pull request merged**
