### PR TITLE
Wandsworth remove 0845 0945 slots

### PR DESCRIPTION
**Pull request by kyliemulholland**

### CODE REVIEW

**Comment by kyliemulholland** [comment]
Tested in preprod - passed.

**Comment by dan-palmer** [comment]
@kyliemulholland Was there a particular reason for removing these times?

**Comment by kyliemulholland** [comment]
@dan-palmer Only that Wandsworth aren't holding visits at those times anymore.

**Comment by kyliemulholland** [comment]
@dan-palmer Can you merge or is there an issue?

**Comment by SteveMarshall** [comment]
@kyliemulholland @dan-palmer was after an explanation of why the change was being made. I've rebased the two commits into one and added the reason you mention in your comment. @dan-palmer, wanna :shipit:?

**Comment by dan-palmer** [comment]
:+1:

**Pull request merged**
