### PR TITLE
Remove kill-switch

### PR DESCRIPTION
**Pull request by EGiataganas**
The killswitch was originally used to enable/disable instant booking. That was removed by #330, so the killswitch is no longer necessary.

### CODE REVIEW

**Comment by dan-palmer** [comment]
Is it worth adding a little context to the commit here? What is the kill switch & why has it been removed?

**Comment by EGiataganas** [comment]
@SteveMarshall ^^

**Comment by SteveMarshall** [comment]
@EGiataganas The killswitch was originally used to enable/disable instant booking. That was removed by #330, so the killswitch is no longer necessary.

**Comment by EGiataganas** [comment]
@SteveMarshall :+1: Thank you very much.

**Comment by threedaymonk** [comment]
So happy to lose this. :joy:

**Comment by SteveMarshall** [comment]
@EGiataganas Might be worth amending your commit message to include the detail of your PR description, too?

**Comment by EGiataganas** [comment]
@SteveMarshall Yeah, ofc. My bad

**Comment by dan-palmer** [comment]
👌

**Pull request merged**
