### PR TITLE
Added ping controller to display build / release information

### PR DESCRIPTION
**Pull request by lukaszraczylo**
Using format shared across other projects to display build information.

Objective: We should be able to monitor current version / release id on PVB project. 
@ashb pointed me to PQ project - https://github.com/ministryofjustice/parliamentary-questions/blob/dev/app/controllers/ping_controller.rb and proposed to follow that pattern.

### CODE REVIEW

**Comment by SteveMarshall** [comment]
@lukaszraczylo Can you update the title/description (and the commit message) to give some context on why you need this as well as what it is? It's hard to know if this is the right solution (or appropriate for merging) without knowing what you're trying to solve by doing it.

**Comment by SteveMarshall** [comment]
Looks good to me; thanks for clarifying the description, @lukaszraczylo! Does this depend on anything, or can it be merged now?

**Comment by ashb** [comment]
This change is standalone - if it's missing the fields in the META it will just have null in the field.

**Comment by SteveMarshall** [comment]
:bomb:…:boom:

**Pull request merged**
